query getPosts {
	posts {
		nodes {
			id
			content
			date
			slug
			status
			title
			author {
				node {
					name
				}
			}
		}
	}
}

mutation editPost($id: ID!, $content: String, $title: String) {
	updatePost(input: { id: $id, content: $content, title: $title }) {
		post {
			content
			title
			id
		}
	}
}
